### ISSUE TITLE
AUTHENTICATION FAILED RuntimeException in BackendlessBroadcastReceiver

### ISSUE THREAD

**Issue by TimOfTheYear** [Backendless/Android-SDK#204]
Seeing the following crash log coming back from users in production. Hasn't manifested a lot, but have gotten several bug reports already. Using Backendless SDK 3.0.15.1

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.example.MyApplication.CustomPushReceiver: java.lang.RuntimeException: AUTHENTICATION_FAILED
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2476)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5135)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.RuntimeException: AUTHENTICATION_FAILED
       at com.backendless.push.BackendlessBroadcastReceiver.onError(BackendlessBroadcastReceiver.java:148)
       at com.backendless.push.BackendlessBroadcastReceiver.handleRegistration(BackendlessBroadcastReceiver.java:292)
       at com.backendless.push.BackendlessBroadcastReceiver.handleIntent(BackendlessBroadcastReceiver.java:159)
       at com.backendless.push.BackendlessBroadcastReceiver.onReceive(BackendlessBroadcastReceiver.java:128)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2469)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5135)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by markpiller** [comment]
The error comes back from google when the devices attempts to register with GCM:
https://github.com/Backendless/Android-SDK/blob/master/src/com/backendless/push/BackendlessBroadcastReceiver.java#L292

**Comment by TimOfTheYear** [comment]
That's great, but why is it throwing a RuntimeException and crashing my app instead of being handled?

**Comment by markpiller** [comment]
It is left for the apps to handle. You can subclass BackendlessBroadcastReceive and add your override for the onError method:
 public void onError( Context context, String message )
  {
    throw new RuntimeException( message );
  }

**Comment by TimOfTheYear** [comment]
👍  👌
